# Generated by Django 5.0.3 on 2024-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('dept', models.CharField(max_length=250)),
                ('esal', models.IntegerField(default=0)),
                ('bonus', models.IntegerField()),
                ('mobile', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
